### PR TITLE
Deployment server

### PR DESCRIPTION
**Pull request by adamstrawson**
Additional task to setup deploymentserver.conf if `splunkforwarder_deployment_server` is defined.

http://docs.splunk.com/Documentation/Splunk/6.5.1/Updating/Configuredeploymentclients

### CODE REVIEW

**Comment by gaieges** [comment]
Hey @adamstrawson .. thanks for the PR.    I have one issue that I've been trying to work out in my head before addressing and this PR relates to it so help me think it through:

In this case, we're modifying an entire config file, however the splunk process also makes its own modifications through user-action or just through normal server usage.  In this case, if we re-ran the script it would blow away all of those other changes.

My thought on how to deal with that is to never deal directly with the entire file itself (I know I sort of do that already), but rather use the `lookup('ini')` method to find and idempotently change a string in the files via `lineinfile`.  

Alternatively, we could do strictly CLI operations but I'm finding that's not nearly as extensive as I want it to be.

Thoughts?

**Comment by adamstrawson** [comment]
Hey @gaieges,

If the concern is about the file being blown away on each run, we could stick with the way I've dealt with this in PR https://github.com/overipio/splunkuf-ansible/pull/2 for inputs.conf, it's similar to how you're thinking about it above too with `lineinfile` and `lookup()`, but instead I'm using `blockinfile` and markers. Ansible will then only change what is within that marker rather than changing the entire file.

If you're thinking of changing a single value that's in the config that hasn't been added by Ansible, then I agree, `lineinfile` would work great for that. Personally I'd use `regexp` instead to find the line though, rather than `lookup()`.

**Comment by gaieges** [comment]
I looked through your other PR and really do like that approach that you're taking, don't get me wrong.  There are two concerns I have with that approach:  In the context of the UF - what happens if you want a different types of splunk forwarder configs (ie non-file-monitors)?

And then secondly, more for files outside of the UF space (ie not a list of homogenous user-provided values) like the `outputs.conf`: how do you ensure that you're modifying the correct stanza within the splunk ini files by using a regex or `lineinfile` without a `lookup()`?

Given that your other PR is a good first step and clearly better than this one, I'm going to merge that, but lets keep this discussion going because I'd like your input.

**Comment by adamstrawson** [comment]
Valid points, I guess I was just thinking about our use case with this. Here's my initial thoughts;

> what happens if you want a different types of splunk forwarder configs (ie non-file-monitors)?

We could make what I've done so far a bit more generic, rather than just for monitors. For example;

```yaml
- splunkforwarder_inputs_input:
   - type: monitor
     type_value: "/hello/world.log"
     settings:          
       sourcetype: app_log
       index: differentindex
   - type: splunktcp
     settings:
       enableS2SHeartbeat: true
       inputShutdownTimeout: 5
```

- `type` is the input type (eg. monitor, batch, tcp, etc)
- `type_value` is optional, if the type is `monitor`, then it'll be a log file, if it's `tcp`, then the IP:PORT for example
- `settings` is a key:value list of input Additional Settings

Which would then translate to;

```
[monitor:///hello/world.log]
index = differentindex
sourcetype = app_log

[splunktcp]
enableS2SHeartbeat = true
inputShutdownTimeout = 5
```

> how do you ensure that you're modifying the correct stanza within the splunk ini files by using a regex or lineinfile without a lookup()

Good question, I know markers with blockinfile solves this, but lineinfile could be tricky, I'm not too sure how Ansible handles it if you regex matches two lines (I know if you have `backref: yes` set it'll modify the last found line, i'll imagine this would be the same with using `lookup()` too. Just had a quick search on Google and couldn't find anything that might solve this. Let me ponder over it though and I'll come back.

**Comment by gaieges** [comment]
Hey @adamstrawson .. sorry for the delay, but I appreciate the thoughts!

I'm going to merge this so it doesn't hold up you taking advantage of it, and let's continue this conversation here (or via email or chat or something) and deal with the inputs in a way that everyone can benefit from.

The deploymentclient can also likely be more dynamic, or at least have a `extra_deploymentclient_config` section where one can override anything about that file.

**Comment by gaieges** [comment]
OK so to follow up on our previous conversation @adamstrawson : I like the way you're thinking about the inputs.  Do you have a spare moment to do that?   If not lmk and I'll get around to it at some point (I'll open an issue for tracking for now).

I'm also thinking that we add an additional value there that allows you to enter ANY other input into that file, similar to the way you're doing the deploymentclient.conf file, but with the additional `{{catchall}}` bucket for any arguments that dont match our format.

Regarding your point about the `ini` check and `lineinfile` trickyness: yeah I think you're right.  I spent a little time playing with this the other day and it's really not easy at all to implement, plus I Think the value that it adds is pretty small.  Let's leave it for now and come back to it if we find the need for it.

**Pull request merged**
